[profile.default]
src = "."
out = "out"
libs = ["lib", "../lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

[rpc_endpoints]
mantle_testnet = "${MANTLE_RPC_URL}"
mantle_mainnet = "https://rpc.mantle.xyz"

[etherscan]
mantle_testnet = { key = "${MANTLESCAN_API_KEY}", url = "https://explorer.sepolia.mantle.xyz/api" }
